<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <ModPath>DiscoAPI</ModPath>
        <LangVersion>default</LangVersion>
    </PropertyGroup>
    
    <Import Project="./config.targets" />
    <Import Project="./disco.targets" />

    <PropertyGroup>
        <Version>0.0.1</Version>
        <Nullable>enable</Nullable>
        <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
        <ExcludeGeneratedDebugSymbol>False</ExcludeGeneratedDebugSymbol>
        <AssemblyName>DiscoAPI</AssemblyName>
        <Description>Modding API for Disco Elysium (separate runtime components only)</Description>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RootNamespace>DiscoAPI</RootNamespace>
        <DefineConstants>DISCOAPI_RUNTIME</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" IncludeAssets="all" />
        
        <Compile Include="src/Common/**/*.cs" />
        <Compile Include="src/Runtime/**/*.cs" />
        <None Include="src/Editor/**/*.cs" />
        <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
    </ItemGroup>

    <Target Name="CopyLooseAssets" AfterTargets="Build">
        <ItemGroup>
            <AssetFiles
                    Include="assets/**/*"
                    Exclude="**/*.meta"/>
        </ItemGroup>

        <Message Text="Copying loose assets to $(OutputFolder):%0A    * @(AssetFiles, '%0A    * ')" Importance="high" />

        <MakeDir Directories="$(OutputFolder)/assets" />
        <Copy SourceFiles="@(AssetFiles)"
              DestinationFolder="$(OutputFolder)/assets/%(RecursiveDir)" />
    </Target>
</Project>
