<Project ToolsVersion="17.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ItemDefinitionGroup>
        <ProjectReference>
            <Private>false</Private>
            <ExcludeAssets>runtime</ExcludeAssets>
        </ProjectReference>
    </ItemDefinitionGroup>

    <PropertyGroup>
        <BepInExCore>$(DiscoElysium)/BepInEx/core</BepInExCore>
        <OutputFolder Condition="'$(OutputFolder)' == ''">$(DiscoElysium)/BepInEx/patchers</OutputFolder>
        
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <TargetFramework>net6.0-windows</TargetFramework>
    </PropertyGroup>
    
    <!--References to BepInEx assemblies-->
    <ItemGroup>
        <Reference Include="$(BepInExCore)/BepInEx.Core.dll" Private="false"/>
        <Reference Include="$(BepInExCore)/BepInEx.Preloader.Core.dll" Private="false"/>
        <Reference Include="$(BepInExCore)/Mono.Cecil.dll" Private="false"/>
        <Reference Include="$(BepInExCore)/Mono.Cecil.Mdb.dll" Private="false"/>
        <Reference Include="$(BepInExCore)/Mono.Cecil.Pdb.dll" Private="false"/>
        <Reference Include="$(BepInExCore)/Mono.Cecil.Rocks.dll" Private="false"/>
        <Reference Include="$(BepInExCore)/MonoMod.RuntimeDetour.dll" Private="false"/>
    </ItemGroup>

    <Target Name="CopyAssembliesToMods" AfterTargets="Build" Condition="Exists('$(TargetDir)$(TargetName).dll')">
        <ItemGroup>
            <ArtefactFiles Include="$(TargetDir)*.dll;$(TargetDir)*.pdb" />
        </ItemGroup>
    
        <Message Text="Copying assemblies to $(OutputFolder):%0A    * @(ArtefactFiles, '%0A    * ')" Importance="high" />    

        <Copy SourceFiles="@(ArtefactFiles)"
              DestinationFolder="$(OutputFolder)/%(RecursiveDir)" />
    </Target>
</Project>

